### ISSUE TITLE
Something wrong when I use a SYCL version (Intel GPUs) AutoDock-GPU

### ISSUE THREAD

**Issue by paraunie** [NiBoyang/AutoDock-SS#5]
1. A SYCL-accelerated version of AutoDock-GPU was used (https://github.com/emascarenhas/AutoDock-GPU). However, an issue occurred after the molecule was converted. The error report states: “cudaGetDevice failed: GetErrorString not supported.” Could this indicate that AutoDock-SS does not support non-CUDA environments?   Additionally, "'CsA_ligand' is not in list", could you help me understand what this means?
```
1 molecule converted
AutoDock-GPU version: v1.5.3-48-g480b4de170c8912fcc99c9d4c39a8317f9001805
Using 12 OpenMP threads
Running 1616 docking calculations on 2 devices
(Thread 2 is setting up Job #271)
(Thread 11 is setting up Job #1483)
(Thread 4 is setting up Job #541)
cudaGetDevice failed GetErrorString not supported
autodock_xegpu_64wi: ./host/src/performdocking.cpp:200: void setup_gpu_for_docking(GpuData &, GpuTempData &): Assertion `0' failed.
(Thread 9 is setting up Job #1215)
(Thread 3 is setting up Job #406)
Aborted (core dumped)
100%|█████████████████████████████████████████████| 25/25 [00:00<00:00, 137.20it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "~/program/AutoDock-SS/adss_main.py", line 300, in <module>
    main()
  File "~/program/AutoDock-SS/adss_main.py", line 286, in main
    sorted_name, sorted_score = normalize_and_sort_scores(name_lis, score_lis, ref_path)
  File "~/program/AutoDock-SS/adss_main.py", line 200, in normalize_and_sort_scores
    ref_ind = name_lis.index(f"{Path(ref_path).stem}")
ValueError: 'CsA_ligand' is not in list
```
2. If something goes wrong, the process will stop. However, if I restart it, I get the error: "FileExistsError: [Errno 17] File exists." The time spent on converting the molecule was very long, so please make the necessary changes.
```
1 molecule converted
Finished creating 'grid.txt'
Finished creating map files
Traceback (most recent call last):
  File "~/program/AutoDock-SS/adss_main.py", line 300, in <module>
    main()
  File "~/program/AutoDock-SS/adss_main.py", line 272, in main
    create_folder_and_initialize_docking_file(lib_path, lig_path)
  File "~/program/AutoDock-SS/adss_main.py", line 122, in create_folder_and_initialize_docking_file
    create_folder(libpath=lib_path)
  File "~/program/AutoDock-SS/file_utils.py", line 11, in create_folder
    os.mkdir(folder_path)
FileExistsError: [Errno 17] File exists: ‘                                        '
```

**Comment by danialshah353** [comment]
After deleting the newly created folder this problem (FileExistsError: [Errno 17] File exists: ) resolved but im also facing this error. try everything i can even from chatgpt but  cannot resolve the error. please letme know if you resolved the erro
aceback (most recent call last):
  File "~/program/AutoDock-SS/adss_main.py", line 300, in <module>
    main()
  File "~/program/AutoDock-SS/adss_main.py", line 286, in main
    sorted_name, sorted_score = normalize_and_sort_scores(name_lis, score_lis, ref_path)
  File "~/program/AutoDock-SS/adss_main.py", line 200, in normalize_and_sort_scores
    ref_ind = name_lis.index(f"{Path(ref_path).stem}")
ValueError: 'CsA_ligand' is not in list
